"""create users branches and stocks tables

Revision ID: 03f8830c10b9
Revises: 
Create Date: 2026-07-21 17:17:32.283511

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03f8830c10b9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('branches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('branches', schema=None) as batch_op:
        batch_op.create_index('uq_branches_name_lower', [sa.literal_column('lower(name)')], unique=True)

    op.create_table('stocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.CheckConstraint('quantity >= 0', name='ck_stocks_quantity_non_negative'),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], name='fk_stocks_branch', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('branch_id', 'product_id', name='uq_stocks_branch_product')
    )
    with op.batch_alter_table('stocks', schema=None) as batch_op:
        batch_op.create_index('ix_stocks_product_id', ['product_id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=True),
    sa.CheckConstraint("role != 'admin' OR branch_id IS NULL", name='ck_users_admin_without_branch'),
    sa.CheckConstraint("role != 'common' OR branch_id IS NOT NULL", name='ck_users_common_with_branch'),
    sa.CheckConstraint("role IN ('admin', 'common')", name='ck_users_role_valid'),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], name='fk_users_branch', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index('uq_users_username_lower', [sa.literal_column('lower(username)')], unique=True)
    op.create_index(
        "uq_users_single_admin",
        "users",
        ["role"],
        unique=True,
        postgresql_where=sa.text("role = 'admin'"),
    )

    # ### end Alembic commands ###


def downgrade():
    op.drop_index(
        "uq_users_single_admin",
        table_name="users",
    )
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('uq_users_username_lower')

    op.drop_table('users')
    with op.batch_alter_table('stocks', schema=None) as batch_op:
        batch_op.drop_index('ix_stocks_product_id')

    op.drop_table('stocks')
    with op.batch_alter_table('branches', schema=None) as batch_op:
        batch_op.drop_index('uq_branches_name_lower')

    op.drop_table('branches')
    # ### end Alembic commands ###
